import React, { useState } from 'react';
import { getMedicinesApi } from '../services/medicineService';
import { getTodayRemindersApi } from '../services/reminderService';
import { useAuth } from '../context/AuthContext';
import { toast } from 'react-hot-toast';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { FileText, Download, FileSpreadsheet, ShieldCheck, Printer, CheckCircle2, Pill } from 'lucide-react';
import Navbar from '../components/common/Navbar';
import Sidebar from '../components/common/Sidebar';
import Footer from '../components/common/Footer';

const ExportPage = () => {
  const { user } = useAuth();
  const [isMobileSidebarOpen, setIsMobileSidebarOpen] = useState(false);
  const [loadingPdf, setLoadingPdf] = useState(false);
  const [loadingCsv, setLoadingCsv] = useState(false);

  // Generate PDF Report using jsPDF & autotable
  const exportPdfReport = async (reportType = 'MEDICATIONS') => {
    setLoadingPdf(true);
    try {
      const doc = new jsPDF();
      const todayStr = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      // Header Banner & Branding
      doc.setFillColor(14, 165, 233); // Sky-500
      doc.rect(0, 0, 210, 30, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('MedReminder 💊', 14, 18);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('Official Medication & Adherence Report', 14, 25);

      // Patient Metadata
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`Patient Name: ${user?.name || 'Patient'}`, 14, 42);
      doc.setFont('helvetica', 'normal');
      doc.text(`Email: ${user?.email || 'N/A'}`, 14, 48);
      doc.text(`Report Date: ${todayStr}`, 14, 54);

      if (reportType === 'MEDICATIONS') {
        const data = await getMedicinesApi();
        const medicines = data.medicines || data || [];

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Active Medication Prescriptions', 14, 66);

        const tableColumn = ['Medicine Name', 'Dosage', 'Frequency', 'Food Timing', 'Status'];
        const tableRows = medicines.map((m) => [
          m.name,
          m.dosage || 'N/A',
          Array.isArray(m.reminderTimes) ? m.reminderTimes.join(', ') : 'Daily',
          m.foodTiming || 'After Food',
          m.status || 'Active',
        ]);

        doc.autoTable({
          startY: 72,
          head: [tableColumn],
          body: tableRows,
          theme: 'striped',
          headStyles: { fillColor: [14, 165, 233], textColor: [255, 255, 255], fontStyle: 'bold' },
        });
      } else {
        const reminders = await getTodayRemindersApi();

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Recent Medication Adherence History', 14, 66);

        const tableColumn = ['Medicine', 'Dosage', 'Scheduled Slot', 'Status', 'Date'];
        const tableRows = (reminders || []).map((r) => [
          r.medicine?.name || 'Medicine',
          r.dosage || '500mg',
          r.timeSlot,
          r.status,
          r.dateString || todayStr,
        ]);

        doc.autoTable({
          startY: 72,
          head: [tableColumn],
          body: tableRows,
          theme: 'striped',
          headStyles: { fillColor: [13, 148, 136], textColor: [255, 255, 255], fontStyle: 'bold' },
        });
      }

      // Footer disclaimer
      const pageCount = doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Generated by MedReminder Healthcare Platform — Page 1 of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 10
      );

      doc.save(`MedReminder_${reportType}_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success(`${reportType} PDF Report downloaded successfully.`);
    } catch (err) {
      console.error('PDF Export Error:', err);
      toast.error('Failed to generate PDF report.');
    } finally {
      setLoadingPdf(false);
    }
  };

  // Export CSV Data
  const exportCsvData = async (type = 'MEDICINES') => {
    setLoadingCsv(true);
    try {
      let csvContent = '';
      let filename = `MedReminder_${type}_${new Date().toISOString().split('T')[0]}.csv`;

      if (type === 'MEDICINES') {
        const data = await getMedicinesApi();
        const medicines = data.medicines || data || [];

        csvContent = 'ID,Name,Dosage,Category,FoodTiming,Status,Doctor\n';
        medicines.forEach((m) => {
          csvContent += `"${m._id}","${m.name}","${m.dosage}","${m.category || 'General'}","${m.foodTiming}","${m.status}","${m.doctorName || ''}"\n`;
        });
      } else {
        const reminders = await getTodayRemindersApi();
        csvContent = 'ID,Medicine,Dosage,TimeSlot,Status,Date\n';
        (reminders || []).forEach((r) => {
          csvContent += `"${r._id}","${r.medicine?.name || ''}","${r.dosage || ''}","${r.timeSlot}","${r.status}","${r.dateString}"\n`;
        });
      }

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.setAttribute('href', url);
      link.setAttribute('download', filename);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      toast.success(`${type} CSV downloaded successfully.`);
    } catch (err) {
      console.error('CSV Export Error:', err);
      toast.error('Failed to export CSV file.');
    } finally {
      setLoadingCsv(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-slate-950">
      <Navbar onToggleMobileSidebar={() => setIsMobileSidebarOpen(!isMobileSidebarOpen)} />

      <div className="flex-1 flex">
        <Sidebar
          isMobileOpen={isMobileSidebarOpen}
          onCloseMobile={() => setIsMobileSidebarOpen(false)}
        />

        <main className="flex-1 md:ml-64 p-4 sm:p-6 lg:p-8 space-y-8 max-w-5xl mx-auto w-full">
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2">
              <FileText className="w-7 h-7 text-sky-500" />
              <span>PDF & Data Export Center</span>
            </h1>
            <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
              Download formal PDF medical reports and CSV data spreadsheets for doctor visits or personal records.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Card 1: Formal PDF Medical Reports */}
            <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800/80 shadow-md space-y-6 flex flex-col justify-between">
              <div className="space-y-4">
                <div className="w-12 h-12 rounded-2xl bg-sky-100 dark:bg-sky-950 text-sky-600 dark:text-sky-400 flex items-center justify-center">
                  <Printer className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">PDF Clinical Reports</h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed">
                    Formatted PDF report including active prescriptions, dosage timings, food conditions, and patient summary.
                  </p>
                </div>
              </div>

              <div className="space-y-3 pt-4 border-t border-slate-100 dark:border-slate-800">
                <button
                  onClick={() => exportPdfReport('MEDICATIONS')}
                  disabled={loadingPdf}
                  className="w-full py-3 rounded-2xl bg-sky-600 hover:bg-sky-500 text-white font-bold text-xs shadow-md flex items-center justify-center space-x-2 transition disabled:opacity-50"
                >
                  <Download className="w-4 h-4" />
                  <span>{loadingPdf ? 'Generating PDF...' : 'Download Prescription PDF'}</span>
                </button>

                <button
                  onClick={() => exportPdfReport('HISTORY')}
                  disabled={loadingPdf}
                  className="w-full py-3 rounded-2xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs flex items-center justify-center space-x-2 transition disabled:opacity-50"
                >
                  <FileText className="w-4 h-4" />
                  <span>Download Adherence History PDF</span>
                </button>
              </div>
            </div>

            {/* Card 2: CSV Data Spreadsheets */}
            <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800/80 shadow-md space-y-6 flex flex-col justify-between">
              <div className="space-y-4">
                <div className="w-12 h-12 rounded-2xl bg-teal-100 dark:bg-teal-950 text-teal-600 dark:text-teal-400 flex items-center justify-center">
                  <FileSpreadsheet className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">CSV Data Spreadsheets</h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed">
                    Raw CSV data exports suitable for Excel, Google Sheets, or electronic health record (EHR) import.
                  </p>
                </div>
              </div>

              <div className="space-y-3 pt-4 border-t border-slate-100 dark:border-slate-800">
                <button
                  onClick={() => exportCsvData('MEDICINES')}
                  disabled={loadingCsv}
                  className="w-full py-3 rounded-2xl bg-teal-600 hover:bg-teal-500 text-white font-bold text-xs shadow-md flex items-center justify-center space-x-2 transition disabled:opacity-50"
                >
                  <Download className="w-4 h-4" />
                  <span>{loadingCsv ? 'Exporting...' : 'Export Medicines CSV'}</span>
                </button>

                <button
                  onClick={() => exportCsvData('HISTORY')}
                  disabled={loadingCsv}
                  className="w-full py-3 rounded-2xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs flex items-center justify-center space-x-2 transition disabled:opacity-50"
                >
                  <FileSpreadsheet className="w-4 h-4" />
                  <span>Export History CSV</span>
                </button>
              </div>
            </div>
          </div>
        </main>
      </div>

      <Footer />
    </div>
  );
};

export default ExportPage;
